name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.2.0]
    steps:
      - uses: actions/checkout@master
      - name: install, build, and test
        run: |
          npm install
          npm run build
        env:
          CI: true
      - name: Deploy to production
        uses: rushadaev/webapp@master
        env:
          AUTHOR: rushadaev
          BUILD_PATH: dist
          GITHUB_PAGE_NAME: rushadaev.github.io/webapp
          PA_TOKEN: ${{ secrets.PA_TOKEN }}
          USERNAME: rushadaev
